export const dataMaterias = [
    {        
        clave: '12102',
        nombre: 'Organización de computadoras y lenguaje ensamblador',
        planEstudios: '20092',
        etapa: 'Disciplinaria',
        carrera: 'Ingeniería en computación',
        caracter: 'Obligatoria',
    },
    {
        clave: '12098',
        nombre: 'Algoritmos y estructuras de datos',
        planEstudios: '20092',
        etapa: 'Disciplinaria',
        carrera: 'Ingeniería en computación',
        caracter: 'Obligatoria',
    },
    {
        clave: '12119',
        nombre: 'Ingeniería de software',
        planEstudios: '20092',
        etapa: 'Terminal',
        carrera: 'Ingeniería en computación',
        caracter: 'Obligatoria',
    },
    {
        clave: '12099',
        nombre: 'Programación orientada a objetos',
        planEstudios: '20092',
        etapa: 'Disciplinaria',
        carrera: 'Ingeniería en computación',
        caracter: 'Obligatoria',
    },
    {
        clave: '12099',
        nombre: 'Programación orientada a objetos',
        planEstudios: '20092',
        etapa: 'Disciplinaria',
        carrera: 'Ingeniería en computación',
        caracter: 'Obligatoria',
    },
    {
        clave: '12099',
        nombre: 'Microprocesadores y microcontroladores',
        planEstudios: '20092',
        etapa: 'Disciplinaria',
        carrera: 'Ingeniería en computación',
        caracter: 'Obligatoria',
    },
    {
        clave: '12124',
        nombre: 'Taller de sistema operativo unix',
        planEstudios: '20092',
        etapa: 'Básica',
        carrera: 'Ingeniería en computación',
        caracter: 'Optativa',
    },
    {
        clave: '12107',
        nombre: 'Inteligencia artificial',
        planEstudios: '20092',
        etapa: 'Disciplinaria',
        carrera: 'Ingeniería en computación',
        caracter: 'Obligatoria',
    },
    {
        clave: '11253',
        nombre: 'Desarrollo de aplicaciones para iphone',
        planEstudios: '20092',
        etapa: 'Terminal',
        carrera: 'Ingeniería en computación',
        caracter: 'Obligatoria',
    },
    {
        clave: '12128',
        nombre: 'Diseño de interacciones',
        planEstudios: '20092',
        etapa: 'Disciplinaria',
        carrera: 'Ingeniería en computación',
        caracter: 'Optativa',
    },
    {
        clave: '12125',
        nombre: 'Programación estructurada',
        planEstudios: '20092',
        etapa: 'Disciplinaria',
        carrera: 'Ingeniería en computación',
        caracter: 'Optativa',
    },
    {
        clave: '12136',
        nombre: 'Sistemas basados en agentes',
        planEstudios: '20092',
        etapa: 'Disciplinaria',
        carrera: 'Ingeniería en computación',
        caracter: 'Optativa',
    }, 
]